// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SofTrust.Report.Infrastructure;

namespace SofTrust.Report.Infrastructure.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20201015124227_RemoveIntersectionReport")]
    partial class RemoveIntersectionReport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Data")
                        .HasColumnName("data")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnName("report_id")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_data_sets");

                    b.HasIndex("ReportId")
                        .HasName("ix_data_sets_report_id");

                    b.ToTable("data_sets");
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Data")
                        .HasColumnName("data")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnName("report_id")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("ReportId")
                        .HasName("ix_data_sources_report_id");

                    b.ToTable("data_sources");
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Data")
                        .HasColumnName("data")
                        .HasColumnType("bytea");

                    b.Property<int>("ReportId")
                        .HasColumnName("report_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("ReportId")
                        .HasName("ix_templates_report_id");

                    b.ToTable("templates");
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.Variable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Data")
                        .HasColumnName("data")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnName("label")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnName("report_id")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_variables");

                    b.HasIndex("ReportId")
                        .HasName("ix_variables_report_id");

                    b.ToTable("variables");
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.DataSet", b =>
                {
                    b.HasOne("SofTrust.Report.Core.Models.Domain.Report", "Report")
                        .WithMany("DataSets")
                        .HasForeignKey("ReportId")
                        .HasConstraintName("fk_data_sets_reports_report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.DataSource", b =>
                {
                    b.HasOne("SofTrust.Report.Core.Models.Domain.Report", "Report")
                        .WithMany("DataSources")
                        .HasForeignKey("ReportId")
                        .HasConstraintName("fk_data_sources_reports_report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.Template", b =>
                {
                    b.HasOne("SofTrust.Report.Core.Models.Domain.Report", "Report")
                        .WithMany("Templates")
                        .HasForeignKey("ReportId")
                        .HasConstraintName("fk_templates_reports_report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SofTrust.Report.Core.Models.Domain.Variable", b =>
                {
                    b.HasOne("SofTrust.Report.Core.Models.Domain.Report", "Report")
                        .WithMany("Variables")
                        .HasForeignKey("ReportId")
                        .HasConstraintName("fk_variables_reports_report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
